### PR TITLE
OMPL with continuous joint state spaces

### PR DESCRIPTION
**Pull request by mklingen**
This adds support for continuous joint state spaces at the expense of some performance. It represents the state space as a compound state of several real vectored states and SO2 state spaces concatenated together

### CODE REVIEW

**Comment by cdellin** [comment]
Would it make sense to maintain two implementations of `RobotStateSpace`, and use the faster `RealVectorStateSpace` if no joints are continuous?

**Comment by mklingen** [comment]
@cdellin yes probably.

**Comment by mkoval** [comment]
Several of the tests on Travis failed. Travis was having reliability issues earlier today, so I restarted the tests in case this was related.

**Comment by mkoval** [comment]
I re-ran tests on [this pull request](https://travis-ci.org/personalrobotics/or_ompl/builds/90191833) and on [`master`](https://travis-ci.org/personalrobotics/or_ompl/builds/88454313). It looks like these changes did indeed break something.

@mklingen Can you run the tests locally and try to figure out what's going on?

**Comment by mklingen** [comment]
Ok. Looks like all the planners failed. Not really sure what state this branch was in.

**Comment by mklingen** [comment]
Actually all the RRT planners succeeded and SBL/KPIECE both failed...

**Comment by mklingen** [comment]
@mkoval  most of my plans are failing because of this:

```
[StateSpace.cpp:715] No default projection is set. Perhaps setup() needs to be called
[OMPLPlanner.cpp:338 PlanPath] Planning failed: No projection evaluator specified
```

So I need to create a custom projector for the compound state space, yeah?

**Comment by mkoval** [comment]
I think the bug is actually the first line:
```
[StateSpace.cpp:715] No default projection is set. Perhaps setup() needs to be called
```
This is the same bug as #34. I'll fix this and see if the issue goes away.

**Comment by mklingen** [comment]
I get the same warning after @mkoval's merge

**Comment by siddhss5** [comment]
Where are we on this? @mklingen, can you work on this during the hackathon today?

**Comment by mklingen** [comment]
We know that a projection function has to be created for the state space. Not sure who was going to do this, but I can look at it this morning.

**Comment by mklingen** [comment]
I pushed a custom projection evaluator. It fixes the "no default projection evaluator" problem, but `KPIECE` still fails to find plans. I think I am not implementing it properly.

**Comment by mkoval** [comment]
The [ompl documentation][(http://ompl.kavrakilab.org/projections.html) says that:

> Most planning algorithms use a data structure (in addition to the tree/graph of motions) for guiding the exploration of the space. In many cases, this data structure is in the form of a discretization of the state space. **For practical purposes, discretizing the state space itself is not feasible, due to its high dimensionality. An approach taken by many algorithms is to use projections from the state space to a low dimensional Euclidean space (Rk, k usually around 2 or 3)**, and discretize that Euclidean space instead. This includes algorithms such as ompl::geometric::EST, ompl::geometric::SBL, ompl::geometric::KPIECE1. This projection can also be thought of as a hash function that maps states to cells in a low dimensional Euclidean space.

My suspicion is that simply returning the vector of projections results in a state space that is too large (e.g. 6 dimensions on ADA) to discretize. Planning SEGFAULTs when it attempts to allocate memory for that grid.

**Comment by mklingen** [comment]
Yeah you're right about that Mike. I'll look at ways of projecting it down to 2 or 3 dimensions instead. I can likely just copy what's going on in `RealVectorStateSpace` and assume the continuous joints are just real-vectors with limits at `-PI` to `PI`. That would make it return suboptimal solutions with a planner like `KPIECE` but still manage the continuous joints with planners like `RRT` which don't require a projection to a low-dimensional space.

**Comment by mklingen** [comment]
tests are now passing locally!

**Comment by mklingen** [comment]
`RRT` fails some percentage of time now because its too slow... otherwise tests are passing

**Comment by mkoval** [comment]
I upped the time limit for the tests and they're now passing on Travis.

**Pull request merged**
