### PR TITLE
Add FMT* and BIT* to list of available planners

### PR DESCRIPTION
**Pull request by DavidB-CMU**
Mentioned in Issue #27

### CODE REVIEW

**Comment by mkoval** [comment]
:+1: Are there any other geometric motion planners that were recently added to OMPL that we should also add to the list?

**Comment by siddhss5** [comment]
At some point it'd be nice to add anytime support to or_ompl. We've been talking about this for a while now.

Sidd.

(Rapidly written in motion)

**Comment by DavidB-CMU** [comment]
@mkoval @siddhss5 See the attached image.
Via `or_ompl` we have access to 20 planners from OMPL.
I tested these with `herbpy` and 2 planners fail to find a solution, and 2 planners cause a crash.
There are another 7 planners and 1 meta-planner in OMPL that are not available through `or_ompl`

ompl_planners_in_or_ompl

**Comment by mkoval** [comment]
@DavidB-CMU Two additional requests, please:

1. add that table to the README, preferably not as an image (use a Markdown list of table)
2. update the list of planners in test_Planners.py accordingly

**Comment by DavidB-CMU** [comment]
@mkoval 
1. Can you check the README here:  https://github.com/DavidB-CMU/or_ompl  
Is that what you were looking for?  
2. Currently the unit test has disabled the planners which "often don't produce a solution".  

Also, BIT* and FMT* aren't supported in the OMPL package that we have installed by default, so I probably should not add them?

**Comment by mkoval** [comment]
1. That looks great! My only request is that you move that table closer to bottom of the README, so it doesn't hide the installation instructions and usage examples.

2. Ideally we would only disable planners that actually have bugs. However, it is important that we don't get too many spurious failures in the unit tests, just because a planner is slow, because it means that the tests will frequently "cry wolf." Were you able to get those planners to ever succeed? Perhaps we can try on a simpler / lower dimensional problem?

3. It should be fine to add BIT* and FMT* to the YAML file. We check if the header file exists before generating the wrapper code, so it should work as expected (i.e. wrap the planners if they're present; do nothing if they're not).

**Comment by mkoval** [comment]
Also, ideally, I'd like to get rid of the "works in HerbPy" column entirely. The or_ompl unit test is intended to be an easy planning problem, so I'm a bit surprised that planners are succeed on HERB that fail on the unit test. Can you take a look at those discrepancies?

**Pull request merged**
