### PR TITLE
Added "enforceBounds" back to RobotStateSpace

### PR DESCRIPTION
**Pull request by mklingen**
in `or_ompl` there are several places where the user explicitly calls "enforceBounds" on the state space. This was removed in the last PR, and I just added it back in.

### CODE REVIEW

**Comment by mkoval** [comment]
I still don't really understand why this is necessary. Shouldn't we be using the methods on `SO2StateSpace` to perform all operations on those values (e.g. compute distances, subtract angles,e tc)? Why do we need them to be in any particular range?

**Comment by mklingen** [comment]
this PR is just calling `enforceBounds` on all the subspaces. `SO2StateSpace` may not do anything, but the `RealVectorStateSpace` will force it inside the bounds.

**Comment by mkoval** [comment]
I see. Do you know how we're getting states that are out of bounds in the first place?

**Comment by mklingen** [comment]
I don't know whether the states end up out of bounds or not. I think the original intention of the `enforceBounds` function was to keep continuous joints between -PI and PI, which is not necessary. I'll close this PR.

**Pull request closed without merging**
