### PR TITLE
or_ompl now prints which planners were found during build

### PR DESCRIPTION
**Pull request by cdellin**

### CODE REVIEW

**Comment by mkoval** [comment]
You're not close()zing either file that you open. Can you switch to using context managers for this?

**Comment by mkoval** [comment]
I'm also not a huge fan of directly embedding ASCII escape codes like they, because it tends to produce ugly results of you redirect the output to a file. However, I don't know of a good way of detecting whether that is the case or not without pulling in another dependency.

@psigen Know of any tricks?

If not, I suppose we can keep it the way it is now.

**Comment by psigen** [comment]
On a separate note, `argparse` is capable of directly typing a `FileType('w')` (https://docs.python.org/3/library/argparse.html#type), so I would suggest doing that, and detecting either a `None` or setting a default of `sys.stdout`.

**Comment by mkoval** [comment]
The Python developers advise against that because it does not properly
close the handle

http://bugs.python.org/issue13824

**Comment by psigen** [comment]
Oh well, then I guess a 'stdout' default is the only way to do it.

@cdellin: addressing the colorization issue, can you use `isatty()`?
http://stackoverflow.com/a/2893767

**Comment by cdellin** [comment]
+1 for those suggestions, implemented.  Also prettified the cpp output a bit and changed the location of the generated cpp file to be in `build/or_ompl/src` instead of `build/src` to avoid collisions with other packages.

**Comment by mkoval** [comment]
:+1: Thanks @cdellin!

**Pull request merged**
